[0m16:42:12.945797 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107d0b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a80f610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11a80f750>]}


============================== 16:42:12.950984 | 6da90097-0e85-4054-8028-82c5fe418373 ==============================
[0m16:42:12.950984 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:42:12.951292 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/ant/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:42:12.965072 [info ] [MainThread]: dbt version: 1.10.4
[0m16:42:12.965286 [info ] [MainThread]: python version: 3.13.3
[0m16:42:12.965420 [info ] [MainThread]: python path: /Users/ant/Documents/dbt_snowflake_project_ELT/.venv/bin/python3
[0m16:42:12.965544 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit-Mach-O
[0m16:42:13.185688 [info ] [MainThread]: Using profiles dir at /Users/ant/.dbt
[0m16:42:13.185937 [info ] [MainThread]: Using profiles.yml file at /Users/ant/.dbt/profiles.yml
[0m16:42:13.186101 [info ] [MainThread]: Using dbt_project.yml file at /Users/ant/Documents/dbt_snowflake_project_ELT/dbt_project.yml
[0m16:42:13.186274 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:42:13.187852 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.28007808, "process_in_blocks": "0", "process_kernel_time": 0.135695, "process_mem_max_rss": "128319488", "process_out_blocks": "0", "process_user_time": 0.71567}
[0m16:42:13.188176 [debug] [MainThread]: Command `dbt debug` failed at 16:42:13.188131 after 0.28 seconds
[0m16:42:13.188333 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b7eefd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b91ac30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11b7d9260>]}
[0m16:42:13.188502 [debug] [MainThread]: Flushing usage events
[0m16:42:13.546382 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:46:43.845780 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10773b4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c2f610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c2f750>]}


============================== 16:46:43.848746 | 39c6c65f-d9f3-44bf-9fec-d2683d54bfe4 ==============================
[0m16:46:43.848746 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:46:43.849028 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': '/Users/ant/.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:46:43.860723 [info ] [MainThread]: dbt version: 1.10.4
[0m16:46:43.860938 [info ] [MainThread]: python version: 3.13.3
[0m16:46:43.861066 [info ] [MainThread]: python path: /Users/ant/Documents/dbt_snowflake_project_ELT/.venv/bin/python3
[0m16:46:43.861183 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit-Mach-O
[0m16:46:44.110056 [info ] [MainThread]: Using profiles dir at /Users/ant/.dbt
[0m16:46:44.110308 [info ] [MainThread]: Using profiles.yml file at /Users/ant/.dbt/profiles.yml
[0m16:46:44.110467 [info ] [MainThread]: Using dbt_project.yml file at /Users/ant/Documents/dbt_snowflake_project_ELT/dbt_project.yml
[0m16:46:44.110639 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m16:46:44.112218 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.30076343, "process_in_blocks": "0", "process_kernel_time": 0.13356, "process_mem_max_rss": "126222336", "process_out_blocks": "0", "process_user_time": 0.723908}
[0m16:46:44.112573 [debug] [MainThread]: Command `dbt debug` failed at 16:46:44.112527 after 0.30 seconds
[0m16:46:44.112737 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10980efd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10993ac30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097fd260>]}
[0m16:46:44.112905 [debug] [MainThread]: Flushing usage events
[0m16:46:44.506004 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:53:36.945161 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111bfb4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11390f610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11390f750>]}


============================== 16:53:36.948270 | 5ab19e33-5661-4245-9d67-1a8bd462c955 ==============================
[0m16:53:36.948270 [info ] [MainThread]: Running with dbt=1.10.4
[0m16:53:36.948563 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '/Users/ant/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt debug', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m16:53:36.960445 [info ] [MainThread]: dbt version: 1.10.4
[0m16:53:36.960665 [info ] [MainThread]: python version: 3.13.3
[0m16:53:36.960808 [info ] [MainThread]: python path: /Users/ant/Documents/dbt_snowflake_project_ELT/.venv/bin/python3
[0m16:53:36.960930 [info ] [MainThread]: os info: macOS-14.5-arm64-arm-64bit-Mach-O
[0m16:53:37.186752 [info ] [MainThread]: Using profiles dir at /Users/ant/.dbt
[0m16:53:37.187000 [info ] [MainThread]: Using profiles.yml file at /Users/ant/.dbt/profiles.yml
[0m16:53:37.187176 [info ] [MainThread]: Using dbt_project.yml file at /Users/ant/Documents/dbt_snowflake_project_ELT/dbt_project.yml
[0m16:53:37.187319 [info ] [MainThread]: Configuration:
[0m16:53:37.187446 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m16:53:37.187567 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m16:53:37.187696 [info ] [MainThread]: Required dependencies:
[0m16:53:37.187858 [debug] [MainThread]: Executing "git --help"
[0m16:53:37.204327 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m16:53:37.204788 [debug] [MainThread]: STDERR: "b''"
[0m16:53:37.204940 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m16:53:37.205095 [info ] [MainThread]: Connection test skipped since no profile was found
[0m16:53:37.205304 [info ] [MainThread]: [31m2 checks failed:[0m
[0m16:53:37.205428 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "data_pipeline", target "dev" invalid: False is not valid under any of the given schemas


[0m16:53:37.205545 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/ant/Documents/dbt_snowflake_project_ELT/dbt_project.yml> not found

[0m16:53:37.207149 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.29612997, "process_in_blocks": "0", "process_kernel_time": 0.136341, "process_mem_max_rss": "126828544", "process_out_blocks": "0", "process_user_time": 0.72045}
[0m16:53:37.207751 [debug] [MainThread]: Command `dbt debug` failed at 16:53:37.207699 after 0.30 seconds
[0m16:53:37.207992 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1148ef100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114a1af90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1148d9260>]}
[0m16:53:37.208186 [debug] [MainThread]: Flushing usage events
[0m16:53:37.633276 [debug] [MainThread]: An error was encountered while trying to flush usage events
